config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  div id="error_explanation"
    div class="alert alert-danger"
      | This form contains #{pluralize(object.errors.count, "error")}!
    ul
      - object.errors.full_messages.each do |msg|
        li #{msg}

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol class="microposts"
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_logged_in_micropost_feed_and_form.html.slim
div class="row"
  aside class="col-md-4"
    section class="user_info"
      = render "shared/user_info"
    section class="stats"
      = render "shared/stats"
    section class="micropost_form"
      = render "shared/micropost_form"
  div class="col-md-8"
    h3 Micropost Feed
    = render "shared/feed"

app/views/shared/_micropost_form.html.slim
= form_for(@micropost, html: { multipart: true }) do |f|
  = render "shared/error_messages", object: f.object
  div class="field"
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-primary"
  span class="picture"
    = f.file_field :picture, accept: "image/jpeg, image/git, image/png"

javascript:
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

app/views/shared/_stats.html.slim
- @user ||= current_user
div class="stats"
  a href="#{following_user_path(@user)}"
    strong id="following" class="stat"
      = @user.following.count
    | following
  a href="#{followers_user_path(@user)}"
    strong id="followers" class="stat"
      = @user.followers.count
    | followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1 #{current_user.name}
span =link_to "view my profile", current_user
span =pluralize(current_user.microposts.count, "micropost")

app/views/shared/_wellcome_signup.html.slim
div class="center jumbotron"
  h1 Wellcome to the Sample App
  markdown:
    ## This is the home page for the [Ruby on Rails Tutorial] sample application.

    [Ruby on Rails Tutorial]: http://www.railstutorial.org
  = link_to "Sign up now!", signup_path, class:"btn btn-lg btn-primary"
= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org'