config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.slim
footer class="footer"
  small
    markdown:
      The [Ruby on Rails Tutorial][rtut] by [Michael Hartl][mh]
      [rtut]: http://www.railstutorial.org/
      [mh]: http://www.michaelhartl.com/
  nav
    ul
      li #{link_to "About", about_path}
      li #{link_to "Contact", contact_path}
      li #{link_to "News", "http://news.railstutorial.org/"}

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-dark bg-inverse"
  div class="container"
    = link_to "sample app", root_path, id: "logo"
    nav
      ul class="nav navbar-nav pull-right"
        li class="nav-item" #{link_to 'Home', root_path, class: "nav-link"}
        li class="nav-item" #{link_to 'Help', help_path, class: "nav-link"}

        - if logged_in?
          li class="nav-item" #{link_to "Users", users_path, class: "nav-link"}
          li class="nav-item dropdown"
            a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"
              ' Account
            ul class ="dropdown-menu"
              li #{link_to "Profile", current_user, class: "dropdown-item"}
              li #{link_to "Settings", edit_user_path(current_user), class: "dropdown-item"}
              li class="dropdown-divider"
              li #{link_to "Log out", logout_path, method: "delete", class: "dropdown-item"}
        - else
          li class="nav-item" #{link_to "Log in", login_path, class: "nav-link"}

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{full_title(yield(:title))}
    = stylesheet_link_tag 'application', media: 'all',
                                         'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    div class="container"
      - flash.each do |message_type, message|
        div class="alert alert-#{message_type}" #{message}
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?